### ISSUE TITLE
Change the UI

### ISSUE THREAD

**Issue by nullity00** [nullity00/yacademy-residents.github.io#1]
## https://reports.yacademy.dev/

![image](https://github.com/nullity00/yacademy-residents.github.io/assets/70228821/416f3cbf-4138-4fba-870b-68114242f68d)

## TODO

- [ ] - Change the logo, get the logo from here : https://github.com/nullity00/zacademy-site/blob/main/src/public/logo.svg
- [ ] - Change the favicon, get it here : https://github.com/nullity00/zacademy-site/blob/main/src/public/favicon.ico
- [ ] - Maintain the same amount of margin on the left & right as here : https://effortless-crepe-67200a.netlify.app/
- [ ] ![image](https://github.com/nullity00/yacademy-residents.github.io/assets/70228821/ebd20fc4-d4a4-4386-9a8a-5a1e60cdc5e8)
- [ ] - Use the font family mentioned here : https://github.com/nullity00/zacademy-site/blob/main/tailwind.config.cjs#L18
- [ ] - Use the text color used here : https://github.com/nullity00/zacademy-site/blob/main/tailwind.config.cjs#L12
- [ ] - Remove those extra lines & make the search bar prettier + the logo has to be in the middle 
- [ ] ![WhatsApp Image 2024-02-22 at 01 36 07_5ec0a533](https://github.com/nullity00/yacademy-residents.github.io/assets/70228821/4640141d-6de4-4899-bafe-a8072347cb0b)
- [ ] - The left bar has to be well spaced
